version: '3'
services:
  db:
    image: mysql:5.7
    user: "1000:50"
    command: --ignore-db-dir=lost+found --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage:/var/lib/mysql/
    ports:
      - "5432:5432"
  web:
    build: .
    #command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec thin start --ssl -p 3000"
    volumes:
      - .:/app:cached
      - /home/vagrant/.local/share/mkcert:/usr/local/share/mkcert
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
